Update compile flags for CAT2 hardware
mfitzpatrick/mplabx-build pull request #2
Opened 2022-12-08 03:58 UTC by Manas1981

This PR adds CAT2  compilation flag during compile time for CAT2 hardware. The Makefile for CAT2 has the string"CAT2" in the makefile name. This string is serached in the file name. If found "-D CAT2" is added to MP_EXTRA_CC_PRE command.

2022-12-10 03:27 UTC, mfitzpatrick requested changes

2022-12-10 03:27 UTC, mfitzpatrick commented on mplabxBuildProject.py
> +  result = makefile.find('CAT2')
Make this generic instead, IMO. Check the environment for a variable `MP_EXTRA_CC_PRE` and pass its contents on to the `make` cmd.

NB: `subprocess.Popen` [documentation](https://docs.python.org/3/library/subprocess.html#subprocess.Popen) has a parameter `env` which takes a dict of environment variables to pass on to the running subprocess. If the makefile makes use of the environment, it is better to set this value in the environment of the `mplabxBuildProject.py` process and explicitly copy the contents across to the subprocess `make` environment via that dict.

2022-12-11 05:33 UTC, Manas1981 commented on mplabxBuildProject.py
> +  result = makefile.find('CAT2')
Set the config variable as enviroment variable "CONF", only for configurations which is not "default". Use this "CONF" env variable to pass a compile flag to MP_EXTRA_CC_PRE.

2022-12-11 11:55 UTC, Manas1981 commented on mplabxBuildProject.py
> +  result = makefile.find('CAT2')
As discussed in the call, I will use the compiler macro  option to set the CAT2 macro for the "CAT2" project. With that setting, no need to change the mpllabxBuildProject.py file.

2022-12-11 11:56 UTC, closed without merging